# Handling program errors

Eventually, you'll have to come to terms with two things:

1.  Your users may type "two" when you ask for a number, "yes" when you ask for a boolean, and anything else that you can't anticipate.
2.  You'll make a mistake in your own code that you didn't expect.

Thanks to the compiler, the second one is less likely. When it comes to syntax errors or a data type mismatch, the IDE indicates that something is wrong with your code. Fortunately, your users never see these. These are called **compiler errors**.

**Runtime errors** are different. They occur when the code runs. The IDE and the compiler won't detect logical errors ahead of time for you, nor can they tell you the printer is out of paper. Runtime errors happen for any number of reasons:

-   You go out of bounds when working with an array
-   The input can't be parsed into a valid data type
-   The email address already exists in the database
-   The server is offline or overloaded
-   The file you try to open doesn't exist

These errors are also often called **exceptions**. An exception is an event, which occurs during the running of a program, that disrupts the normal flow of the program's instructions.

You can limit some of these through **_defensive programming_** but as a programmer, it's your job to make sure that the ones that you can't prevent don't negatively affect your users' experience.

The last thing that you want your users to see is this error message. They may think something malicious has happened:

```shell
Exception in thread "main" java.lang.NumberFormatException: For input string: "cat"
    at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.base/java.lang.Integer.parseInt(Integer.java:652)
    at java.base/java.lang.Integer.parseInt(Integer.java:770)
    at com.techelevator.Program.main(Program.java:6)
```

---

# Exception handling

Java includes the capability to help you handle any unexpected or exceptional situations while your program runs. The practice of anticipating these anomalies and addressing them is called **exception handling**.

When users interact with applications, you must expect them to make mistakes. If you don't, you're in for a surprise. In their defense, they expect your application to indicate that something went wrong, not display a cryptic error message.

When applications implement exception handling, they allow you:

-   The ability to display specific error messages
-   To notify other programmers that your code didn't finish its work

Without proper exception handling, exceptions go uncaught and can potentially reveal information about your program that you don't want your users to see.

There are a few things to know when it comes to working with exception handling:

1.  Exceptions are **_raised_** or **_thrown_**.
2.  Control of the program stops abruptly, and the exception bubbles up until it's **_caught_**.
3.  A **_caught_** exception handles the error and displays the message to the user or logs it.

The next lesson describes some approaches to implementing exception handling in your programs.

---

# Try-catch

When you need to write code where there might be an exception, you use the `try` and `catch` keywords to handle the potential error:

```java
try {
    System.out.print("Enter a number: ");
    String s = input.nextLine();
    int result = Integer.parseInt(s);

    System.out.println("The number typed in is " + result + ".");
} catch (Exception e) {
    System.out.println("An error occurred.");
}

System.out.println("Thank you.");
```

**Example with valid input**

```
Enter a number: 2
The number typed in is 2.
Thank you.
```

**Example with invalid input**

```
Enter a number: two
An error occurred.
Thank you.
```

When a program throws an exception, the runtime finds the nearest `catch` statement to handle the exception. If the current method doesn't have a try-catch block, the exception **_bubbles up_** and looks for a `catch` block in the calling method. If an exception occurs, the remaining code in the `try` block doesn't run.

If there isn't an exception, the `try` block completes successfully and the `catch` block doesn't run.

>âœ” Tip: Consider variable scope
>
>Try-catch blocks work with variable scope the same way that other blocks do. If you need a variable to be available to your entire try-catch block, you'll need to declare it in advance.

---

# Exception object

Java provides an _exception_ object with the details about the exception that was thrown. This object is an instance of the `Exception` class, or one of its many subclasses. The details of the exception can be accessed using the object's methods.

>ðŸ›ˆ Info: Exceptions built on the principle of inheritance
>
>```
>Object
>    Throwable
>        Exception
>            RuntimeException
>                IllegalArgumentException
>                NumberFormatException
>                ArithmeticException
>                NullPointerException
>                IndexOutOfBoundsException
>                ...
>```
>
>The number of built-in exception classes is far too many to show here. This is just a sample. The Oracle JavaDocs has the full `RuntimeException` hierarchy available. Look under the list of direct known subclasses, [`RuntimeException:Exception` subclass](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/RuntimeException.html)

Using the example from the previous section, you'll catch a `NumberFormatException`, which is thrown when a call to one of the `parse` methods can't complete:

```java
try {
    System.out.print("Enter a number: ");
    String s = input.nextLine();
    int result = Integer.parseInt(s);

    System.out.println("The number typed in is " + result + ".");
} catch (NumberFormatException e) {
    System.out.println("An error parsing the input.");
}

System.out.println("Thank you.");
```

**Example with valid input**

```
Enter a number: 2
The number type in is 2.
Thank you.
```

**Example with invalid input**

```
Enter a number: two
An error occurred parsing the input.
Thank you.
```

You can configure the `catch` block to look for a specific type of exception. It catches anything that's of type `NumberFormatException` or inherits from `NumberFormatException`.

Notice this looks like a method call with a parameter that represents the object that contains the detail about the exception that occurred.

In sum, you should catch exceptions when you understand how you want to recover from it.

## Exception properties

The [Exception](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Exception.html) class is the base class from which all exceptions inherit. It contains the following properties to help you understand how exceptions work:

| **Property Name** | **Description**                                                                          |
| ----------------- | ---------------------------------------------------------------------------------------- |
| `Cause`           | Used to create and preserve a series of exceptions caught during exception handling.     |
| `Message`         | Provides detail about the cause of the exception.                                        |
| `StackTrace`      | Contains a **_stack trace_** that can determine where the error occurred.                |

Each of the properties are accessible with their corresponding gettersâ€”`getCause()`, `getMessage()`, and `getStackTrace()`.

Most of the classes that inherit from `Exception` don't add additional properties or methods. They inherit from `Exception` to allow as specific of error handling as possible.

The next section looks at two particular properties to demonstrate their usefulness.

### Message

The `Message` property describes the exception in further detail:

-   Most exception messages explain **_the reason for the exception_**. They aren't guaranteed to be user-friendly.
-   With custom exceptions, you can set your own message.

### Stack trace

A stack trace is a list of method calls the application had pending when the exception occurred. Having a stack trace is extremely important. You don't want to troubleshoot production issues without seeing the original error take place.

If you look at a sample Java stack trace, you can see its value:

```
Exception in thread "main" java.lang.NullPointerException
        at com.example.myproject.Book.getTitle(Book.java:16)
        at com.example.myproject.Author.getBookTitles(Author.java:25)
        at com.example.myproject.Bootstrap.main(Bootstrap.java:14)
```

The stack trace acts like a trail of breadcrumbs so that you can determine where the `NullPointerException` occurred in your code. If you start with the first line beginning with "at", you'll see the name of the class, method, and the line number that caused the `NullPointerException`.

In this case it's this line:

```
at com.example.myproject.Book.getTitle(Book.java:16)
```

You use this by observing what file it references and look directly at the line. In this case, the error occurred in `Book.java` on line 16:

```java
15   public String getTitle() {
16      System.out.println(title.toLower());
17      return title;
18   }
```

A `NullPointerException` occurs when you try to invoke a property or method on an object whose value is null. It looks like `title` may have been null.

>âš  Danger: Stack traces give a lot away
>
>Stack traces can be dangerous if observed by customers or users in production. You should use error screens to show when something goes wrong. If a malicious user saw a stack trace, they'd have information that can compromise your application, like the technology used, the libraries your code relies on, and internal naming conventions.

In sum: read the stack trace. It'll save you time.

---

# Finally

While the Java runtime handles most memory management for you, sometimes you need to dispose of resources when you're done with them.

For example:

-   Databases have a finite number of connections. Your applications need to close connections when done with them.
-   Files are "locked" when opened, prohibiting other applications from seeing or making modifications.
-   You may need to release lower-level graphics resources.

You know when exceptions are thrown, the statements in the `catch` block are called and your program never returns to the `try` block. The `catch` block might return from the method itself or throw additional exceptions. It's possible that code after the try-catch may never run and resources are never cleared out:

```java
try {
    // Code that may throw an exception
} catch (IOException e) {
    // Code that catches the exception
}

// Code that is not guaranteed to execute
```

Java provides the `finally` block, which you can add to a try-catch. Statements inside of a `finally` block run whether an exception occurred or not:

```java
try {
    // Code that may throw an exception
} catch (IOException e) {
    // Code that catches the exception
} finally {
    // Code that executes whether an exception
    // is thrown or not.
}
```

---

# Raising exceptions

In addition to handling exceptions, you can raise your own exceptions using the `throw` keyword.

The most common scenario where you want to throw your own exception is when your code can't complete what it needs to do. This may be due to a null parameter, a value not in a valid range, or any other possible reason.

As an example, the `Clock` constructor allows you to pass any integer as the hour, minute, and second. You need to indicate when a value isn't within the acceptable value range. If you find one, you can throw an exception:

```java
public class Clock {
    public Clock(int hour, int minute, int second) {
        if (hour > 24 || hour < 0)
            throw new IllegalArgumentException("Hour parameter must be between 0 and 24");
        if (minute > 60 || minute < 0)
            throw new IllegalArgumentException("Minute parameter must be between 0 and 60");
        if (second > 60 || second < 0)
            throw new IllegalArgumentException("Second parameter must be between 0 and 60");

        this.Hour = hour;
        this.Minute = minute;
        this.Second = second;
    }
}
```

## Custom exceptions

You're not limited to working with the system exception classes built into Java. If your application needs additional detail, you can create a custom exception. **_This is often the case when you're releasing code for other developers to incorporate._**

Consider a hypothetical vending machine. When the customer decides to purchase an item, many things could go wrong:

-   The item is **_out of stock_**.
-   The customer has **_insufficient funds_**.
-   The customer selects an **_invalid slot_**.
-   The vending machine experienced a **_mechanical dispensing error_**.

Rather than returning `null` or nothing at all, it's possible to throw an exception. The user interface part of your program can determine the best way to display a message to the user, letting them know something went wrong.

## Creating a custom exception

Here are some best practices for creating exceptions:

-   All exceptions inherit from `Exception`.
-   It's a convention to end all custom exceptions with the word `Exception`.
-   The custom exception must define at least these three constructors:
    -   A default constructor.
    -   A constructor that accepts the message property.
    -   A constructor that sets the message property and the "cause" exception.

The following code sample has a custom exception called `InsufficientFundsException`:

```java
public class InsufficientFundsException extends Exception {
    public InsufficientFundsException() {
        super();
    }
    public InsufficientFundsException(String message) {
        super(message);
    }
    public InsufficientFundsException(String message, Exception cause) {
        super(message, cause);
    }
}
```

Usually, you create and throw an exception in a single line of code, like:

```
throw new InsufficientFundsException("balance is short $25.72");
```

Your code can catch this exception using `catch (InsufficientFundsException e)`:

```java
try {
    // ...
}
catch (InsufficientFundsException e) {
    System.out.println(e.getMessage()); // prints "balance is short $25.72"
}
```

---

# Catching multiple exceptions

A number of different exceptions could occur with your code. The syntax for a try-catch statement allows one or more `catch` blocks.

Doing this allows you to address each of the exceptions in different ways:

```java
try {
    // Perform some work, such as opening a file and reading all of the text.
} catch (FileNotFoundException e) {
    // If the file doesn't exist, that exception is handled here.
} catch (IOException e) {
    // A general IO exception is handled here, such as being unable to read the file.
}
```

When the exception occurs from within the `try` block, it immediately stops and looks for the nearest `catch` block that matches the exception type. If you define the more generic exception instead of a specific exception first, you risk losing the ability to execute exception-specific code.

In sum:

-   It's best practice to catch a specific type of exception.
-   Place your catch blocks in order of most specific to least specific.
-   Avoid catching the base `Exception` class.

---

# Defensive programming

Exception handling is extremely useful and can help you avoid scenarios which may worry your users or make them think something bad happened.

Still, you can't rely on the runtime to tell you when there's a problem. If you can avoid the exception through **_defensive programming_**, you should at all costs.

Here are a few ways to avoid exceptions:

| **Exception**                      | **How to Prevent It**                                                                                                                                                                                               |
| ---------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `ArrayIndexOutOfBoundsException`   | Confirm that your index is within the bounds of the array or list first.                                                                                                                                           |
| `ArithmeticException`              | Make sure that your divisor isn't equal to 0 first.                                                                                                                                                                 |
| `NullPointerException`             | Check if the reference object you're acting on is `!= null` before calling any properties or methods on it.                                                                                                         |
| `FileNotFoundException`            | Use `File.Exists()` before accessing a folder or file that might not exist due to bad input or something deleted.                                                                                                   |
| `IllegalArgumentException`         | Use user-interface validation first to inform the user that they typed in an invalid value and to try again. This doesn't remove the need for an `IllegalArgumentException`, but it cuts down on the occurrences.   |

---

# Unit summary

In this unit you learned:

-   How to handle exceptions with `try`, `catch`, and `finally`.
-   What's revealed within a stack trace and how it helps you troubleshoot your code.
-   Throwing built-in and custom exceptions.
-   Guarding against exceptions through defensive programming.

---

# Quiz

## **Exception Handling 1**

**An exception is ________**

â—‹ An error that occurs as you write and compile code.

â—‹ Code that runs when a particular condition is false.

â—‰ An error that occurs as your program is running.

â—‹ When the user receives an error message.

**Explanation:** Also called a runtime error, an exception occurs when your program is running.


## **Exception Handling 2**

**Select all of the following that describe benefits of exception handling:**

	Select all correct options

â–  Display a specific and clear error message to the user.

â–¡ Check if a file exists before opening it.

â–  Signal to other code that your code didn't complete.

â–¡ Prevent going out of bounds with an array.

â–  Allow your program to continue running.


## **Exception Handling 3**

**Which options would be displayed by the following code?**

```java
try {
    System.out.println("One");
    throw new Exception();
    System.out.println("Two");
} catch (Exception e) {
    System.out.println("Three");
}

System.out.println("Four");
```

	Select all correct options

â–  One

â–¡ Two

â–  Three

â–  Four

**Explanation:** The "Two" isn't printed because an exception is thrown before the line runs. The "Three" **_is_** printed because the `catch` block runs when the exception is thrown.


## **Exception Handling 4**

**Because `FileNotFoundException` extends `IOException` which also extends `Exception`, they have all of the same methods and properties of `Exception`. This is an example of what OOP principle?**

â—‹ Polymorphism

â—‰ Inheritance

â—‹ Cohesion

â—‹ Encapsulation

**Explanation:** A subclass "inherits" all the properties and methods of its superclass.


## **Exception Handling 5**

**Which options would be displayed by the following code?**

```java
try {
    System.out.println("One");
    throw new IllegalArgumentException();
    System.out.println("Two");
} catch (IllegalArgumentException e) {
    System.out.println("Three");
} catch (Exception e) {
    System.out.println("Four");
}

System.out.println("Five");
```

	Select all correct options

â–  One

â–¡ Two

â–  Three

â–¡ Four

â–  Five

**Explanation:** The "Two" isn't printed because an exception is thrown before the line runs. The "Four" isn't printed because the exception that's thrown is an `IllegalArgumentException` which has its own `catch` that prints the "Three" line.


## **Exception Handling 6**

**Which options would be displayed by the following code?**

```java
try {
    System.out.println("One");
    System.out.println("Two");
} catch (Exception e) {
    System.out.println("Three");
} finally {
    System.out.println("Four");
}

System.out.println("Five");
```

	Select all correct options

â–  One

â–  Two

â–¡ Three

â–  Four

â–  Five

**Explanation:** The "Three" isn't printed because an exception isn't thrown. The "Four" is printed because it's in a `finally` block that always runs whether an exception is thrown or not.


## **Exception Handling 7**

**What's displayed by this code?**

```java
try {
    String inputNumber = "five";
    int result = Integer.parseInt(inputNumber);
    System.out.println("The number is " + result);
} catch (NumberFormatException e) {
    System.out.println("Invalid number format");
} catch (Exception e) {
    System.out.println("Exception occurred");
}
```

â—‹ The number is 5

â—‹ The number is five

â—‰ Invalid number format

â—‹ Exception occurred

**Explanation:** The `Integer.parseInt()` method can't parse a number written out as a word, which causes a `NumberFormatException` to occur. There's no other output.


## **Exception Handling 8**

**It's safe to display a stack trace to a user.**

â—‹ True

â—‰ False

**Explanation:** A stack trace can reveal sensitive information about your code that a malicious user can use against your application. Also a stack trace isn't helpful or meaningful to non-programming end users, so it's best to not show it to any end users.


## **Exception Handling 9**

**If this exception was thrown:**

```java
throw new IllegalArgumentException("Parameter isn't a valid value");
```

**How would you access the string passed to it in this `catch` block?**

```java
catch (IllegalArgumentException e) {

}
```

â—‹  `e.getCause()`

â—‹  `e.toString()`

â—‰  `e.getMessage()`

â—‹  `e.getStackTrace()`

**Explanation:** The `Message` property often contains the reason for the exception, which can be provided by Java or overridden by passing a string to the exception's constructor.
